version: '3.8'

services:
  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - discovery-server
      - auth-service
      - customer-service
      - account-service
      - transaction-service

  discovery-server:
    build:
      context: ./discovery-server
    ports:
      - "8761:8761"

  auth-service:
    build:
      context: ./auth-service
    ports:
      - "8081:8081"

  customer-service:
    build:
      context: ./customer-service
    ports:
      - "8082:8082"

  account-service:
    build:
      context: ./account-service
    ports:
      - "8083:8083"

  transaction-service:
    build:
      context: ./transaction-service
    ports:
      - "8084:8084"