spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/customers/**
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/accounts/**
        - id: transaction-service
          uri: lb://transaction-service
          predicates:
            - Path=/transactions/**
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
  security:
    oauth2:
      client:
        registration:
          auth-service:
            client-id: your-client-id
            client-secret: your-client-secret
            scope: read,write
            authorization-grant-type: password
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          auth-service:
            authorization-uri: http://auth-service/oauth/authorize
            token-uri: http://auth-service/oauth/token
            user-info-uri: http://auth-service/userinfo

server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/